# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f89f119016602a010233b48b57a7a0a2b5ed8fdd358660f5df2bcfccfff7a357de087c4ce84bd608a6addc5fd9c6f4f0afd63eec67556ea171459ef9f678162a

test:
  secret_key_base: 82cb04a6e5799f4c514255a21a6a32790745675099d5e7d9006c93b644e8d37e9d3b357080d5b414267514c4d61460e0515cb05c0c308245cde1a5d659a39469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
